# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 976a8c86b052f7c040ab58ebcac507399fd77d205b1bd57546bbe0572c7e4622fc5f06a8a7fe1bf4d570b1ac49a3adc214b15658c7f0dc03768aad9d0315bdab

test:
  secret_key_base: 2dc4700477e656631d4b87a8bd91ab683c1afd325a776531ad271609870a1c32c743316d51d703376e4f05b30573489ad7e5cd2581eff508156d5f9789d5f20b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
